src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArtistRepository::class)
 */
class Artist
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $link;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $share;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $picture_small;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $picture_medium;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $picture_big;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $picture_xl;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nm_album;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_fan;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $radio;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $tracklist;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(?int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getShare(): ?string
    {
        return $this->share;
    }

    public function setShare(?string $share): self
    {
        $this->share = $share;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPictureSmall(): ?string
    {
        return $this->picture_small;
    }

    public function setPictureSmall(?string $picture_small): self
    {
        $this->picture_small = $picture_small;

        return $this;
    }

    public function getPictureMedium(): ?string
    {
        return $this->picture_medium;
    }

    public function setPictureMedium(?string $picture_medium): self
    {
        $this->picture_medium = $picture_medium;

        return $this;
    }

    public function getPictureBig(): ?string
    {
        return $this->picture_big;
    }

    public function setPictureBig(?string $picture_big): self
    {
        $this->picture_big = $picture_big;

        return $this;
    }

    public function getPictureXl(): ?string
    {
        return $this->picture_xl;
    }

    public function setPictureXl(?string $picture_xl): self
    {
        $this->picture_xl = $picture_xl;

        return $this;
    }

    public function getNmAlbum(): ?int
    {
        return $this->nm_album;
    }

    public function setNmAlbum(?int $nm_album): self
    {
        $this->nm_album = $nm_album;

        return $this;
    }

    public function getNbFan(): ?int
    {
        return $this->nb_fan;
    }

    public function setNbFan(?int $nb_fan): self
    {
        $this->nb_fan = $nb_fan;

        return $this;
    }

    public function getRadio(): ?bool
    {
        return $this->radio;
    }

    public function setRadio(?bool $radio): self
    {
        $this->radio = $radio;

        return $this;
    }

    public function getTracklist(): ?string
    {
        return $this->tracklist;
    }

    public function setTracklist(?string $tracklist): self
    {
        $this->tracklist = $tracklist;

        return $this;
    }
}

templates/Artistes/addArtist.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}

<label for="mercure-message-input">Artiste:</label>
<input type="text" id="artist-name"/>
<input onclick="search()" type="button" id="artist-btn" value="Send"/>

<section id="texte"></section>

<script>
    var section = document.querySelector('section');
    
    function search(){
        document.getElementById("texte").innerHTML = "";
        var text = document.getElementById('artist-name').value;
        var requestURL = 'http://localhost/deezer_api/public/index.php/search/' + text;
        var request = new XMLHttpRequest();
        request.open('GET', requestURL);
        request.responseType = 'json';
        request.send();
        request.onload = function() {
        var artiste = request.response;
        showTable();
        showArtist(artiste);
    }
    }


    function showTable() {
        var table = document.createElement("table");
        var thead = document.createElement("thead");
        var tbody = document.createElement('tbody');
        var tr = document.createElement("tr");
        var img = document.createElement("th");
        var id = document.createElement("th");
        var name = document.createElement("th");
        var nbfan = document.createElement("th");
        var add = document.createElement("th");

        table.setAttribute('class','table');
        tbody.setAttribute('id','value');
        img.setAttribute('scope','col');
        id.setAttribute('scope','col');
        name.setAttribute('scope','col');
        nbfan.setAttribute('scope','col');
        add.setAttribute('scope','col');
        img.textContent = "Image";
        id.textContent = "ID";
        name.textContent = "Name";
        nbfan.textContent = "Nb fan";
        add.textContent = "add";

        table.appendChild(thead);
        table.appendChild(tbody);
        thead.appendChild(tr);
        tr.appendChild(img);
        tr.appendChild(id);
        tr.appendChild(name);
        tr.appendChild(nbfan);
        tr.appendChild(add);

        section.appendChild(table);
    }

    function showArtist(jsonObj) {
        var obj = jsonObj['data'];

        for (var i = 0; i < obj.length; i++) {
            var url = '{{ path("addArtist", {"id": 'region_id'}) }}'; 
            url = url.replace("region_id", obj[i].id); 
            var tbody = document.querySelector('tbody');
            var tr = document.createElement('tr');
            var id = document.createElement('th');
            var name = document.createElement('th');
            var nbfan = document.createElement('th');
            var thimg = document.createElement('th'); 
            var img = document.createElement('img');
            var thadd = document.createElement('th');
            var add = document.createElement('a');


            thimg.setAttribute('scope','col');
            id.setAttribute('scope','col');
            name.setAttribute('scope','col');
            nbfan.setAttribute('scope','col');
            id.textContent = obj[i].id;
            name.textContent = obj[i].name;
            nbfan.textContent = obj[i].nb_fan;
            add.textContent = "Add";
            img.setAttribute("src", obj[i].picture_small );
            add.setAttribute("href",url)

            tr.appendChild(thimg);
            tr.appendChild(id);
            tr.appendChild(name);
            tr.appendChild(nbfan);
            tr.appendChild(thadd);
            thimg.appendChild(img);
            thadd.appendChild(add);

            tbody.appendChild(tr);
        }
        
    }


</script>
{% endblock %}

templates/Artistes/listArtist.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!{% endblock %}

{% block body %}
<h1>Artist</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Picture</th>
      <th scope="col">id</th>
      <th scope="col">Name</th>
      <th scope="col">Link</th>
      <th scope="col">Nb album</th>
      <th scope="col">Nb fan</th>
      <th scope="col">#</th>
    </tr>
  </thead>
  <tbody>
    {% set a = 1 %}
    {% for artist_n in artist %}
        <tr>
            <th scope="row">{{a}}</th>
            <td><img src="{{artist_n.pictureSmall}}"</td>
            <th scope="row">{{artist_n.id}}</th>
            <td>{{artist_n.name}}</td>
            <td><a href="{{artist_n.link}}" target="_blank">{{artist_n.link}}</a></td>
            <td>{{artist_n.nmalbum}}</td>
            <td>{{artist_n.nbfan}}</td>
            <td><a href="{{ path("newTrack", {"artist": artist_n.id }) }}">Voir plus</a></td>
            {% set a = a + 1 %}
        </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}